# Generated by Django 5.0.2 on 2024-03-25 14:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0003_remove_lesson_content_alter_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(default=1234),
            preserve_default=False,
        ),
    ]
